name: Auto Dependency Bot
on:
  schedule:
    - cron: '0 0 * * *'  # UTC 00:00 = KST 09:00
  workflow_dispatch:

jobs:
  renovate:
    runs-on: rebel-k8s-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v39.0.2
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_PLATFORM: github
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}