name: Auto Code Review

on:
  pull_request:
  issue_comment:
    types: [created]
  push:
    branches:
      - '**'

env:
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  GOOGLE_MODEL_ID: ${{ vars.GOOGLE_MODEL_ID }}

jobs:
  check-trigger:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
      pr_number: ${{ steps.check.outputs.pr_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Check if review should run
        id: check
        run: |
          echo "should_run=false" >> $GITHUB_OUTPUT
          
          # For push events, check commit message
          if [[ "${{ github.event_name }}" == "push" ]]; then
            if [[ "${{ contains(github.event.head_commit.message, '[autoreview]') }}" == "true" ]]; then
              echo "should_run=true" >> $GITHUB_OUTPUT
              # Use GitHub CLI to find PR associated with this commit
              gh pr list --head ${{ github.ref_name }} --json number --jq '.[0].number' > pr_number.txt
              if [ -s pr_number.txt ]; then
                echo "pr_number=$(cat pr_number.txt)" >> $GITHUB_OUTPUT
              fi
            fi
          
          # For PR events, just pass through the PR number
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          
          # For comment events, check if it's "/autoreview"
          elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            if [[ "${{ github.event.issue.pull_request != null }}" == "true" && "${{ contains(github.event.comment.body, '/autoreview') }}" == "true" ]]; then
              echo "should_run=true" >> $GITHUB_OUTPUT
              echo "pr_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-review:
    needs: check-trigger
    if: needs.check-trigger.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-generativeai PyGithub

    - name: Run Auto Code Review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ needs.check-trigger.outputs.pr_number }}
      run: python .github/scripts/auto_code_review.py