name: Debug Workflow

on:
  pull_request_review:
    types: [created, edited]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"