name: Deploy package on tag released

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy-on-tag:
    uses: ./.github/workflows/deploy.yaml
    with:
      version: ${{ github.ref_name }}
    secrets: inherit

  trigger-vllm-model-compilation:
    name: trigger vllm model compile and generation ci
    needs: [deploy-on-tag]
    runs-on: rebel-k8s-runner
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'rebellions-sw',
              repo: 'rebel_compiler',
              workflow_id: 'rebel_dispatch_model_generation_for_vllm.yaml',
              ref: 'dev',
              inputs: {
                optimum_rbln_version: ${{ github.ref_name }},
              }
            })
            console.log(result)
