name: PR Checklist Validator

on:
  pull_request:
    branches: [main]
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"
      - "examples/**/*.py"

jobs:
  validate-pr-checklist:
    runs-on: ubuntu-latest-rbln
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          
      - name: Validate PR checklist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python .github/scripts/validate_pr_checklist.py