name: Optimum-rbln / Dispatch / Diffusion

on:
  workflow_call:
    inputs:
      ref:
        description: "ref to checkout"
        required: false
        type: string
      pr_number:
        description: "PR number to run"
        required: false
        type: string
      rebel_compiler_version:
        description: "rebel_compiler version to run"
        required: true
        type: string

env:
  REBEL_PYPI_ENDPOINT: ${{ vars.REBEL_PYPI_INTERNAL_ENDPOINT }}
  REBEL_PYPI_USERNAME: ${{ secrets.REBEL_PYPI_USERNAME }}
  REBEL_PYPI_PASSWORD: ${{ secrets.REBEL_PYPI_PASSWORD }}

jobs:
  diffusion-test:
    name: Diffusion test
    runs-on: vm-ci-0
    steps:
      - name: Checkout the optimum-rbln repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.pr_number && format('refs/pull/{0}/merge', inputs.pr_number) || inputs.ref }}
          submodules: recursive
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Setup Python
        run: uv python install 3.9

      - name: Install optimum-rbln with tests group dependencies
        run: |
          uv sync --frozen --group tests --reinstall-package optimum-rbln

      - name: Install rebel-compiler
        run: |
          PYPI_URL=$(echo ${{ env.REBEL_PYPI_ENDPOINT }} | sed "s/\/\//\0${{ env.REBEL_PYPI_USERNAME}}:${{ env.REBEL_PYPI_PASSWORD}}@/")
          uv pip install --extra-index-url $PYPI_URL rebel-compiler==${{ inputs.rebel_compiler_version }}

      - name: Install requirements
        run: |
          uv pip install -r tests/requirements_sdxl.txt

      - name: Image Generation Test
        run: |
          uv run --no-sync python tests/run_stable_diffusion_xl_base.py
          curl -o sdxl_gt_img.png https://rbln-public.s3.ap-northeast-2.amazonaws.com/images/sdxl_gt_img.png
          uv run --no-sync python tests/psnr.py --img1=sdxl_gt_img.png --img2=rbln_img.png
